### ISSUE TITLE
Repeat four times

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#111]
URL's IPv4 serializer uses this phrase and then in the loop it asks whether it's the fourth time (and then doesn't prepend a dot). Should that be rewritten or formalized?

**Comment by domenic** [comment]
I guess what this is asking for is a for loop, or at least a range version. Otherwise it's rather verbose to say

> 1. Let _i_ be 1.
> 2. While _i_ <= 4:
>     1. ...
>     2. If _i_ is 3
>     3. Set _i_ to _i_ + 1.

In this particular case you could get away with

> 1. For each _i_ in « 1, 2, 3, 4 »:
>     1. ...
>     2. If _i_ is 4.

but that's kind of a weird use of lists (i.e. the list doesn't represent anything real).

If I were to come up with a prose version of a for loop... I guess I'd say

> 1. **Repeat for** _i_ ranging from 1 to 4 inclusive:
>     1. ...
>     2. If _i_ is 4.

(Or maybe just "for"?)

Or we could just not sweat it and say everyone understands. At some point formalizing the language feels like diminishing benefit, I dunno.

**Comment by annevk** [comment]
Python actually has something like a range constructor for this and it indeed returns a list. Maybe

"For each i in the range 1 to 4, inclusive:"

which would align with how we define ranges normally.

**Comment by domenic** [comment]
Now that you write that out, it's a really nice solution. I suggest we add the range concept to lists, note that it's mostly used for loops, and add an example, probably in the iteration section but maybe in the lists section.

I wonder if we should comment about 1-based ranges vs. 0-based ranges. For the simple example here 1-based makes more sense. But I guess if you were planning on indexing into a collection 0-based would make more sense. Maybe best to leave it out.
