### ISSUE TITLE
Insertion into lists

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#116]
If I want to define step 6.1 of https://dom.spec.whatwg.org/#concept-node-insert as mutating an underlying list (children of a node is already stated to be a list as well) I need to be able to insert.

Is that acceptable? Or is that problematic for some reason?

Having this will help fix https://github.com/whatwg/dom/issues/174. The alternative I can think of is that I replace the entire list with a new list and just move the items across. Since nothing actually holds a pointer to the actual list (other than data structures DOM controls) that could probably work as well, but would be rather elaborate.

**Comment by domenic** [comment]
It's a very reasonable concept. I'd go with "insert after index n" as the most generic concept, but maybe that is not convenient for DOM and we should consider something else?

One interesting difference between the generic Infra case and the DOM case is that in Infra a list can contain the same item multiple times, whereas in DOM trees that is not the case. So DOM's phrasing of "Insert node into parent before child" doesn't work in general since child could occur multiple times.

**Comment by annevk** [comment]
I think index is fine, since DOM has https://dom.spec.whatwg.org/#concept-tree-index. Though I guess what you say also argues for using a set in DOM.
