### ISSUE TITLE
In parallel

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#120]
In #56 it came up that we don't have conventions for "in parallel" described. 

I actually think we should have "threads" instead of "in parallel" that can run tasks or a sequence of tasks and message back, rather than just an unlimited number of threads spawned with "in parallel" that lead to all kinds of race conditions when not used properly. See also https://github.com/whatwg/html/issues/1843.

It might make sense to describe this concept here, but maybe since it often relates to execution IDL or HTML is a better place.

**Comment by domenic** [comment]
My instinct is that this is specific to browser-like user agents and should go in HTML as such as part of HTML defining the event loop. E.g. it does not apply to network-parser style specs, which otherwise could use most everything in Infra. Or in general to specs that apply in event-loop-less environments.

**Comment by annevk** [comment]
Most specifications interact with the event loop in some way, including Fetch (goes in parallel, but really it's a dedicated networking thread on which we also have service workers), URL (has to be synchronous), and Encoding (streams stuff), but keeping it in HTML seems fine.
