### ISSUE TITLE
Named arguments and especially named optional arguments

### ISSUE THREAD

**Issue by domenic** [whatwg/infra#320]
This is a special case of #92.

Non-named boolean parameters are kind of a pain. Consider HTML's [obtain a worker/worklet agent](https://html.spec.whatwg.org/#obtaining-a-worker/worklet-agent). Call sites for it look like:

> Return the result of obtaining a worker/worklet agent given _outside settings_, _isShared_, and true.

You have to go refer to the algorithm to find out what the true is. (It's "can block".) This is kind of bad, and [is discouraged in programming languages](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap). Perhaps worse, you might think that the second argument is about being shared or not, but really what's happening is that we're passing in the value of _isShared_ for the _isTopLevel_ parameter to the original algorithm. The fact that the second argument is about top-levelness is totally lost.

I can imagine a variety of solutions:

0. Do nothing, and continue without named parameters.

1. Define a struct, e.g. containing "is top level" and "can block", and require callers to construct such a struct. Example: [navigation params](https://html.spec.whatwg.org/#navigation-params). This is not great; it's heavyweight for the caller, and feels like an abuse of structs.

2. Pass an Infra map. E.g. "Return the result of obtaining a worker/worklet agent given _outside settings_, «[ "is top level" → _isShared_, "can block" → true ]»." This is unprecedented, and feels like a bit of an abuse of maps, but maybe OK?

3. Define a new pattern for named parameters. For example:

	> To **obtain a worker/worklet agent**, given an environment settings object or null _outside settings_, a boolean **is top level**, and a boolean **can block**:
	> 1. Let _agentCluster_ be null.
	> 2. If [is top level] is true, then set _agentCluster_ to a new [agent cluster].
	> 3. ...
	>
	> and later someone uses it:
	>> ... return the result of [obtaining a worker/worklet agent] given _outside settings_, [is top level] set to _isShared_, and [can block] set to true.

	(here using bold to denote what would be `<dfn>`s, and brackets to denote what would be `<a>`s.)
	
	What I mildly dislike about this is that we no longer have variable names for some of our arguments; instead we refer to some of them with links. That's a bit weird. Maybe there's a fix?

What do people think of these?

----

This problem becomes more urgent when you want to have optional named parameters. HTML's [navigate](https://html.spec.whatwg.org/#navigate) already has one ("exceptions enabled flag"), and would benefit from at least two more, in its current formulation: replacement enabled (boolean), and navigation type ("form-submission" or "other"). Optionality seems important here; it would be very nice if we didn't have to pass "other" every time we had a non-form-submission navigation.

Of the above solutions, most of them work pretty well with optional named parameters. (1) could define defaults in its struct definition. (2) and (3) would involve some work in the algorithm to say something about if the map entry doesn't exist/the argument wasn't passed, then pick a default.

There is one other solution for this particular problem, though, which might be worth keeping in mind: define wrapper algorithms. So for example, we could define "internal navigate" which takes a non-optional navigation type, and then define "navigate" which calls "internal navigate" with navigation type of "other", and "form navigate" which calls "internal navigate" with navigation type of "form-submission". This might be a good thing, e.g. "form navigate" might never use replacement enabled or exceptions enabled. But in the general case it might be a bad thing; if all parameters are independent, then this leads to a combinatorial explosion of wrapper algorithms (imagine "form-replacement-with-exceptions navigate" vs. "form-replacement navigate" vs. "form navigate" vs. "form-with-exceptions navigate").

---

Anyway, it'd be good to straighten this out, as we start tidying up navigation in HTML.

**Comment by jugglinmike** [comment]
One other consideration for the third option is differentiating like-named parameters across algorithms. We're expecting at least three "navigation enabled" parameters, for example. Callers will have to specify which one they mean. It's a small annoyance, but maybe one that Wattsi could be extended to accommodate this and disambiguate.

Still, the third option seems like the best to me.

Is there a reason we can't define named parameters using `<dfn><var>`, referencing them inside the algorithm via `<var>` and outside the algorithm via `<span>`?

**Comment by domenic** [comment]
> Is there a reason we can't define named parameters using `<dfn><var>`, referencing them inside the algorithm via `<var>` and outside the algorithm via `<span>`?

That's a great idea. I wonder if we should name them **_likeVariables_** or **_like definitions_**? A minor point though; overall this seems like the right route.

**Comment by annevk** [comment]
I would prefer like variables as they are more variables than definitions.

**Comment by annevk** [comment]
Writing down some thoughts on the discussion in #325 (the PR for this issue) to see if that helps.

* It seems that there's a case for non-optional named boolean arguments to provide more clarity at various call sites. This makes me wonder, is this specific to booleans?
* At the same time, we're adding an example with an optional unnamed/positional boolean argument.
* There's a question whether optional boolean arguments should always have a default and whether that default should always be false. (In my opinion, yes and yes.) It seems there's agreement on explicitly stating the defaults over having type-specific defaults in Infra.

I guess the minimal change I'd like to say is requiring a default for optional boolean arguments whether named or unnamed.

If we can figure out a good guideline between the first two bullet points that makes things easier for editors that would be ideal, but if we feel the need for flexibility (which might end up with a wish-wash of styles) I can live with that.

@jyasskin @hober you might have thoughts here too.

**Comment by jyasskin** [comment]
2¢:
* I favor naming arguments any time the type of the argument doesn't fully express its meaning. So, most booleans, integers, strings, maps, records, URLs, etc. should be named. (An exception would be things like setTitle(document, string), where it's "obvious" even to readers.) Even more-semantically-typed arguments should be named if there are two things of the same type in the parameter list, since that's a sign that the type doesn't fully express the meaning anymore. 
* We shouldn't add an example with the dispreferred use. :)
* I agree that having an absent boolean behave differently from true or false is undesirable. If an algorithm wants that, it should define a tristate enum instead. An optional-boolean-that-defaults-to-false seems to match the semantics of "flag" parameters, for example in https://dom.spec.whatwg.org/#dispatching-events. I suspect Infra should endorse flag parameters and suggest phrasing optional booleans as flags.

More generally, I'd like to maximize the chance that this design can allow our tools to automatically check our algorithm calls. I suspect the proposal in #325 is pretty close to that, but I'd like to see some explicit feedback from @tabatkins and @marcoscaceres/@sidvishnoi on what would make their jobs easier.

**Comment by domenic** [comment]
Previously we've discussed (not sure where) moving away from "flags" since they are just weird booleans which necessitate lots of boolean <-> flag conversions. So let's continue with Infra ignoring those, and hoping they eventually all go away.

I'll make the change on requiring that optional boolean arguments have a default false specified.

I'm unsure whether to disrecommend against positional booleans (or positional strings, etc.). I'll try pointing out that they're unclear; TBD how that recommendation comes out...

**Comment by tabatkins** [comment]
Yes, the more arguments that are named, the better, imo. I think we should go the Python route, with all arguments *implicitly* named at the definition site; algorithms can be called with positional arguments if that's clear at the call site, but every single argument can be named explicitly if that's clearer.

My rough plan (with all particulars still up for debate, especially the names) is that `<div algorithm>` blocks will define an algorithm, with `<dfn arg>` defining the arguments. Attributes on the arg definition can specify their type and their optionality.

Then call sites use a fake element `<call>`. The first child autolink (or an explicitly marked-up `<algo>` child, if necessary) is taken as the algo name; I resolve the autolink as normal, and use that to look up the algorithm details.  Inside of `<call>` you mark up arguments with `<arg>`, containing autolinks to arg dfns (or nothing, indicating a positional arg) and `<var>` for values.  (I'll also start tracking |var| types in some way.)

Using this info, I can (a) verify that the algo exists, and isn't marked as deprecated; (b) verify that all the required args are provided; (c) verify that arguments have the correct type.  I can also show, on hover, argument types, and the return type of the algorithm call itself.  Maybe show something like a dfn-panel for the call, with all the information marked up neatly.

----

Agree on using booleans rather than flags; flags are weird bools and I don't like them.

Also agree on having optional booleans have a default of false as a guarantee.

**Comment by jyasskin** [comment]
I withdraw my suggestion to endorse flags and like the alternative of requiring optional booleans to default to false. :)

**Comment by annevk** [comment]
That sounds great. My one piece of feedback is that it would be great if `<div algorithm>` would not be required and `<dfn whatever>` in a paragraph optionally followed by a list would work as well.

**Comment by domenic** [comment]
`<div algorithm>` has existing variable-highlighting benefits, and we should probably be using it more in WHATWG specs. We moved to using it in Streams and it's been quite nice; e.g. click on any of the variables in https://streams.spec.whatwg.org/#readable-stream-pipe-to

**Comment by annevk** [comment]
Fair, maybe it is time.

**Comment by domenic** [comment]
I realized there is another Bikeshed issue (which @inexorabletash raised offline but I misunderstood at the time). The `<a><var>navigationType</var></a>` syntax for naming parameters at their call sites will likely generate a variable-only-used-once warning in Bikeshed. This makes sense, because the containing algorithm isn't really using _navigationType_ as a variable (e.g., it is never declared); it's referencing a variable-of-sorts declared in the "navigate" algorithm, elsewhere.

Probably we should have Bikeshed special-case that markup pattern, and ignore it for the purpose of per-algorithm variable-counting?

(Separately: `<a><var>x</var></a>` vs. `<var><a>x</a></var>` is a bit annoying... the former seems slightly more "right", but it'll be easy to mess up.)

**Comment by annevk** [comment]
It seems `<call>` that Tab mentioned above could help with that, though I'm not entirely sure what the full model would be.

**Comment by domenic** [comment]
Yeah, I was thinking more about the immediate problem if people start using this in today's specs without `<call>`.

**Comment by tabatkins** [comment]
I can always add the notation now even before I hook it up to algo definitions.

**Comment by jyasskin** [comment]
As another example of parameter names helping at call sites, I was recently reviewing https://github.com/WICG/webpackage/pull/591 which had a step of

```
Let |requestForMatch| be the result of [=creating a potential-CORS request=] given |linkTarget|, the empty string, and [=No CORS=].
```

That "empty string" is a [destination](https://fetch.spec.whatwg.org/#concept-request-destination), but to notice that, I had to be reviewing the preview, not just the text, and I had to click through to the algorithm definition. If the original author had been encouraged to pass parameters by name, it would have been much more obvious that there was a mistake there.

Adding `<call>` to the spec generators will probably _increase_ the importance of naming parameters, because it'll remove the other reason reviewers have to click through all the algorithm references, to check that there are the right number and type of parameters.

**Comment by jakearchibald** [comment]
> Yeah, I was thinking more about the immediate problem if people start using this in today's specs without `<call>`.

What's the benefit of using `<var>` here at all? It isn't a variable, and it already links to the definition, so it seems correct semantically.

**Comment by domenic** [comment]
They are variables, at least in the algorithm that uses them.

**Comment by jakearchibald** [comment]
```js
function someFunction({ foo, bar }) {
  // I think it's fair to call `foo` and `bar` variables here.
  console.log(foo, bar);
}

someFunction({ foo: 'hello', bar: 'world' });
// I don't think it's right to call `foo` and `bar` variables here.
```

Within a function, I think it's fair to treat named arguments as variables. However, I don't think named parameters are variables. They aren't declared, they don't have a scope, and they can't be set after declaration.
