### ISSUE TITLE
Deal with profiles in definition/use of user agent

### ISSUE THREAD

**Issue by jyasskin** [whatwg/infra#400]
Several specifications have text like

> [A user agent holds a storage shed](https://storage.spec.whatwg.org/#storage-sheds)

> [A user agent holds a browsing context group set](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-group-set)

where we probably want one per browser profile / incognito or guest session / Firefox container / etc, instead of one per installation. (and definitely not one per [implementation](https://infra.spec.whatwg.org/#user-agent)!) We should do something to make sure that the text in specifications is clear about this.

It's not obvious whether we should redefine "user agent" to make the existing text correct, or introduce a new term and update all the uses.

**Comment by annevk** [comment]
The way I see those features is that they are essentially each their own user agent, managed by something else. From that perspective it's not clear we need to do anything here, but it's probably worth having at least some text as it comes up now and then.

See also https://github.com/whatwg/html/issues/1143.

cc @mnot

**Comment by mnot** [comment]
yeah, user agent != browser implementation. There's one user (well, there are potentially billions, but this is our anchor) and they can have many different agents at the same time. Some might run on the same codebase, address space, machine, network, etc. -- all of those boundaries aren't terribly meaningful, because these things tend to get blurry.

Clarifying that an implementation of the web platform on the browser side might simultaneously instantiate many agents for a given user is probably a good thing.
