### ISSUE TITLE
What was the motive in choosing algorithm description approach?

### ISSUE THREAD

**Issue by LeonidVasilyev** [whatwg/infra#82]
Infra Standard defines [pseudocode and algorithm description approach](https://infra.spec.whatwg.org/#algorithms) that is different from what I usually find in [academic papers](https://www.cs.umd.edu/~samir/498/vitter.pdf) or classic books like [Introduction to Algorithms](https://mitpress.mit.edu/books/introduction-algorithms). Standard also notes that described algorithms aren't intended to be performant:

> Conformance requirements phrased as algorithms or specific steps may be implemented in any manner, so long as the end result is equivalent. (In particular, the algorithms are intended to be easy to follow, and not intended to be performant.)

What was the motive in choosing this specific style of algorithms description?

**Comment by annevk** [comment]
I think in part because English prose is always the way it's been done, so formalizing around that seems less disruptive than inventing a syntax. But English prose also tends to be more readable and leaves more room for being creative in case you need to do something novel. Furthermore, if we had a syntax such as used in that paper, we'd then have to standardize that syntax fully and be constrained by it. Typically what I find is that such pseudocode is not actually defined in detail and therefore more ambiguous than English.

The reason why we don't go for performance is because that is really complicated. E.g., consider the JavaScript standard. If they had to concern themselves with performance they'd have to define JITs, a dozen string types, etc. For CSS you might end up having to define multiple selector matching engines and fiddle with them over time as the characteristics of the web change. It's much easier to describe input -> output and leave the bits between to be optimized as implementations see fit. That also allows completely novel implementation approaches such as Servo.

**Comment by domenic** [comment]
@annevk, I think the last paragraph there could be morphed into a useful non-normative note in the spec. Less sure about the first one.

**Comment by annevk** [comment]
@LeonidVasilyev are you okay with closing this? The standard now includes a note on performance. I'm not quite sure what to say about pseudocode other than using it meaning we'd have to define how that works (and how you extend it), etc.

**Comment by LeonidVasilyev** [comment]
@annevk yes, thank you.
